<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\EmployeeData.TeamsBot.Application.ConversationAi\EmployeeData.TeamsBot.Application.ConversationAi.csproj" />
    <ProjectReference Include="..\EmployeeData.TeamsBot.Domain.Interfaces\EmployeeData.TeamsBot.Domain.Interfaces.csproj" />
    <ProjectReference Include="..\EmployeeData.TeamsBot.Domain.Services\EmployeeData.TeamsBot.Domain.Services.csproj" />
    <ProjectReference Include="..\EmployeeData.TeamsBot.Domain.Models\EmployeeData.TeamsBot.Domain.Models.csproj" />
    <ProjectReference Include="..\EmployeeData.TeamsBot.Domain.Constants\EmployeeData.TeamsBot.Domain.Constants.csproj" />
    <ProjectReference Include="..\EmployeeData.TeamsBot.Application.EmployeeDataApi\EmployeeData.TeamsBot.Application.EmployeeDataApi.csproj" />
    <ProjectReference Include="..\EmployeeData.TeamsBot.Application.Graph\EmployeeData.TeamsBot.Application.Graph.csproj" />
    <ProjectReference Include="..\EmployeeData.TeamsBot.Application.Handlers\EmployeeData.TeamsBot.Application.Handlers.csproj" />
    <ProjectReference Include="..\EmployeeData.TeamsBot.Application.Models\EmployeeData.TeamsBot.Application.Models.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AdaptiveCards" Version="3.1.0" />
    <PackageReference Include="Microsoft.Bot.Builder.Integration.AspNet.Core" Version="4.23.1" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
